# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-22 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
