# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-27 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_incidenttemplate_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='ip_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='ip_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
