# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_auto_20170227_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
