# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_auto_20170303_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttemplate',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='incident',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
