# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_auto_20170303_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttemplate',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
