# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_incidenttemplate_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ip_sortable',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenttemplate',
            name='ip_sortable',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
